baseURL = 'https://blog.annhuiching.com/'
locale = 'en-us'
title = 'Blog'
theme = 'PaperMod'
[[menu.main]]
  name = "annhuiching.com"
  url = "https://annhuiching.com"
  weight = 10
buildFuture = true
buildPast = true
