baseURL = 'https://blog.annhuiching.com/'
locale = 'en-us'
title = 'Ann Hui Ching'
theme = 'PaperMod'
[[menu.main]]
  name = "annhuiching.com"
  url = "https://annhuiching.com"
  weight = 10
buildFuture = true
buildPast = true
cd ~/blog
git add hugo.toml
git commit -m "rename title to Blog"
git push
